Update sync-data.mdx
Error: Could not verify webhook: Expected payload to be of type string or Buffer. Please refer to https://docs.svix.com/receiving/verifying-payloads/how for more information.

This was the error occuring because of payload can be Buffer or string only so i used json.stringify to fix that and it worked